# Phase B1 (DRG default-route-table ownership proof). These tests verify
# the RESOURCE MODEL's shape under mock_provider -- they cannot and do not
# prove import semantics (mock_provider has no concept of "already exists
# live"; the real plan against actual OCI state is the only authoritative
# source for that, per the B1 gate report's own Real Import-Only Plan
# section). What's checked here: the resource references the right DRG,
# self-discovers the right OCI-fixed display name (no tenancy-specific
# OCID anywhere in this module), and the module's overall DRG route-table
# footprint stays exactly what B1 authorizes -- no third custom table, no
# attachment change.

mock_provider "oci" {
  override_data {
    target = data.oci_core_services.all
    values = {
      services = [
        {
          id          = "ocid1.service.oc1..aaaaaaaamockallservices"
          name        = "All EU-MADRID-1 Services In Oracle Services Network"
          cidr_block  = "all-eu-madrid-1-services-in-oracle-services-network"
          description = "mock -- REQ-NET-008 Service Gateway target"
        },
      ]
    }
  }

  override_data {
    target = data.oci_core_drg_route_tables.vcn_default
    values = {
      drg_route_tables = [
        {
          id                               = "ocid1.drgroutetable.oc1..aaaaaaaamockvcndefault"
          drg_id                           = "ocid1.drg.oc1..aaaaaaaamockdrg"
          display_name                     = "Autogenerated Drg Route Table for VCN attachments"
          import_drg_route_distribution_id = "ocid1.drgroutedistribution.oc1..aaaaaaaamockdistribution"
          is_ecmp_enabled                  = false
          state                            = "AVAILABLE"
        },
      ]
    }
  }
}

variables {
  compartment_ocid = "ocid1.compartment.oc1..aaaaaaaaexampleexampleexampleexampleexampleexampleexampleaaaa"
  environment      = "lab"
}

run "vcn_default_route_table_references_the_module_drg" {
  command = plan

  assert {
    condition     = oci_core_drg_route_table.vcn_default.drg_id == oci_core_drg.this.id
    error_message = "the ownership-proof resource must reference this module's own DRG, not a hardcoded/foreign OCID"
  }
}

run "vcn_default_route_table_self_discovers_ocis_fixed_display_name" {
  command = plan

  assert {
    condition     = oci_core_drg_route_table.vcn_default.display_name == "Autogenerated Drg Route Table for VCN attachments"
    error_message = "must target OCI's own fixed auto-generated display name -- the same string used by data.oci_core_drg_route_tables.vcn_default's filter, so self-discovery and the resource model agree"
  }

  assert {
    condition     = data.oci_core_drg_route_tables.vcn_default.drg_id == oci_core_drg.this.id
    error_message = "the self-discovery data source must filter on this module's own DRG, not a hardcoded/foreign OCID"
  }
}

# "No third custom DRG route table in B1" is a source-level invariant
# (exactly two named oci_core_drg_route_table resources exist in
# gateways.tf: inert and vcn_default -- grep-verifiable, not a runtime
# plan assertion: neither resource uses count/for_each, so there is no
# "how many instances" value a plan-based test could meaningfully check
# beyond what the two runs below already establish about each one
# individually).

run "no_drg_attachment_under_b1_defaults" {
  command = plan

  # Uses this file's default variables (manage_inert_drg_route_table
  # defaults to false -- matches the real 10-network deployment's
  # current state). REQ-NET-009 (Phase 26 of the B1-closeout prompt)
  # requires the DRG attachment to genuinely not exist during B1, not
  # merely stay pointed at the old inert table -- confirmed here.
  assert {
    condition     = length(oci_core_drg_attachment.vcn) == 0
    error_message = "B1 requires the DRG attachment to not exist -- attaching (to inert OR to vcn_default) is explicitly out of scope for B1"
  }

  assert {
    condition     = length(oci_core_drg_route_table.inert) == 0
    error_message = "B1 must not plan the custom inert table either, under real-deployment default variables"
  }

  # What this run does NOT and cannot test:
  # - That the real `import` block (which lives in the Terragrunt live
  #   layer's generate block, not in this module) resolves cleanly
  #   against live OCI state -- mock_provider has no live state to import
  #   from. Verified instead by a real scratch-config plan against the
  #   live DRG route table (see the B1 gate report's Real Import-Only
  #   Plan section) and, once credentials allow it, a real plan against
  #   the actual 10-network remote state.
  # - That remove_import_trigger is absent from this resource block --
  #   that's a static source-text invariant (grep-verifiable: `grep
  #   remove_import_trigger infrastructure/modules/network/gateways.tf`
  #   returns nothing), not a runtime-plannable one; B2 is the only phase
  #   authorized to introduce it, and only after B1's ownership is
  #   independently verified.
  # - That the second (RPC/VC/IPSec) auto-generated DRG route table stays
  #   unmanaged -- trivially true by construction (this module never
  #   declares a resource or data source referencing it), not something
  #   a plan-based assertion can meaningfully express.
}
