# Positive tests for SPEC-NET-002 (REQ-NET-006..010): the four gateway
# objects and the DRG's inert configuration (reuse-and-strip form --
# resolves GAP-NET-004).

mock_provider "oci" {
  override_data {
    target = data.oci_core_services.all
    values = {
      services = [
        {
          id          = "ocid1.service.oc1..aaaaaaaamockallservices"
          name        = "All EU-MADRID-1 Services In Oracle Services Network"
          cidr_block  = "all-eu-madrid-1-services-in-oracle-services-network"
          description = "mock -- REQ-NET-008 Service Gateway target"
        },
      ]
    }
  }

  override_data {
    target = data.oci_core_instances.software_nat
    values = {
      instances = []
    }
  }

  override_data {
    target = data.oci_core_drg_route_tables.vcn_default
    values = {
      drg_route_tables = [
        {
          id                               = "ocid1.drgroutetable.oc1..aaaaaaaamockvcndefault"
          drg_id                           = "ocid1.drg.oc1..aaaaaaaamockdrg"
          display_name                     = "Autogenerated Drg Route Table for VCN attachments"
          import_drg_route_distribution_id = "ocid1.drgroutedistribution.oc1..aaaaaaaamockdistribution"
          is_ecmp_enabled                  = false
          state                            = "AVAILABLE"
        },
      ]
    }
  }
}

variables {
  compartment_ocid            = "ocid1.compartment.oc1..aaaaaaaaexampleexampleexampleexampleexampleexampleexampleaaaa"
  environment                 = "lab"
  use_managed_nat             = true
  use_managed_service_gateway = true
}

run "internet_gateway_enabled" {
  command = plan

  assert {
    condition     = oci_core_internet_gateway.this.enabled == true
    error_message = "REQ-NET-006: the Internet Gateway must exist and be enabled"
  }
}

run "nat_gateway_exists" {
  command = plan

  assert {
    condition     = oci_core_nat_gateway.this[0].vcn_id == oci_core_vcn.this.id
    error_message = "REQ-NET-007: the NAT Gateway must be attached to the platform VCN"
  }
}

run "service_gateway_targets_all_services" {
  command = plan

  assert {
    condition     = tolist(oci_core_service_gateway.this[0].services)[0].service_id == "ocid1.service.oc1..aaaaaaaamockallservices"
    error_message = "REQ-NET-008: the Service Gateway must target the OCI Services Network CIDR label, resolved via data.oci_core_services, not hardcoded"
  }
}

run "drg_exists_and_is_attached" {
  command = plan

  assert {
    condition     = oci_core_drg_attachment.vcn.drg_id == oci_core_drg.this.id
    error_message = "REQ-NET-009: the DRG must be attached to the VCN"
  }

  assert {
    condition     = tolist(oci_core_drg_attachment.vcn.network_details)[0].type == "VCN"
    error_message = "REQ-NET-009: the DRG attachment must attach the VCN specifically"
  }
}

run "drg_route_table_is_inert" {
  command = plan

  assert {
    condition     = oci_core_drg_attachment.vcn.drg_route_table_id == oci_core_drg_route_table.vcn_default.id
    error_message = "REQ-NET-009/ADR-0008 (amended): the DRG attachment must reference the reused auto-created VCN-attachments table, stripped of its import distribution"
  }

  assert {
    condition     = oci_core_drg_route_table.vcn_default.remove_import_trigger == true
    error_message = "REQ-NET-009's no-propagation requirement: the reused table's default 'accept all routes' import distribution must be stripped (remove_import_trigger)"
  }

  assert {
    condition     = oci_core_drg_route_table.vcn_default.drg_id == oci_core_drg.this.id
    error_message = "the reused route table must belong to this module's own DRG, not a hardcoded/foreign OCID"
  }

  assert {
    condition     = oci_core_drg_route_table.vcn_default.display_name == "Autogenerated Drg Route Table for VCN attachments"
    error_message = "must target OCI's own fixed auto-generated display name -- the same string data.oci_core_drg_route_tables.vcn_default filters on, so self-discovery and the resource model agree"
  }

  # What this run does NOT and cannot test: that
  # import_drg_route_distribution_id is actually null after apply
  # (REQ-NET-009's "no propagation" end state). mock_provider synthesizes
  # a plausible fake value for every computed attribute regardless of
  # config -- confirmed empirically (the mock always returns a non-null
  # synthetic ID here, identical in kind to the
  # defined_tags/ignore_changes constraint documented in
  # infrastructure/modules/foundation/tests/state_bucket_tag_ownership.tftest.hcl).
  # The only source of truth for "genuinely stripped" is the real
  # provider: verified by the post-apply OCI CLI check (oci network
  # drg-route-table get -- import-drg-route-distribution-id == null)
  # recorded in the PR evidence. Also grep-verifiable: this module
  # declares no oci_core_drg_route_distribution and no
  # oci_core_drg_route_table_route_rule resource, so the table carries
  # zero static routes and nothing can propagate into it once stripped.
}

run "drg_attachment_exports_nothing" {
  command = plan

  assert {
    condition     = oci_core_drg_attachment.vcn.remove_export_drg_route_distribution_trigger == true
    error_message = "inert must hold in both directions: the attachment's default export route distribution must be nulled so nothing is advertised to the VCN attachment (ADR-0008 amendment)"
  }
}

run "no_custom_inert_table_anymore" {
  command = plan

  # The custom oci_core_drg_route_table.inert resource is removed, not
  # gated: reuse-and-strip consumes zero per-DRG route-table quota, so
  # there is no service-limit reason to keep a disabled-by-default code
  # path. Source-level invariant (grep-verifiable): exactly one
  # oci_core_drg_route_table resource exists in gateways.tf
  # (vcn_default). Plan-level assertion: the attachment is unconditional
  # and requires no variable to enable it.
  assert {
    condition     = oci_core_drg_attachment.vcn.drg_id == oci_core_drg.this.id
    error_message = "the DRG attachment must be unconditional -- reuse-and-strip removed the quota constraint that previously forced gating (GAP-NET-004)"
  }

  assert {
    condition     = oci_core_drg.this.display_name == "platform-drg"
    error_message = "the DRG object itself is unconditional"
  }
}

run "gateways_carry_no_oracle_managed_tag_keys" {
  command = plan

  assert {
    condition = alltrue([
      !anytrue([for k in keys(oci_core_internet_gateway.this.defined_tags) : strcontains(k, "Oracle-Tags")]),
      !anytrue([for k in keys(oci_core_nat_gateway.this[0].defined_tags) : strcontains(k, "Oracle-Tags")]),
      !anytrue([for k in keys(oci_core_service_gateway.this[0].defined_tags) : strcontains(k, "Oracle-Tags")]),
      !anytrue([for k in keys(oci_core_drg.this.defined_tags) : strcontains(k, "Oracle-Tags")]),
      !anytrue([for k in keys(oci_core_drg_route_table.vcn_default.defined_tags) : strcontains(k, "Oracle-Tags")]),
      !anytrue([for k in keys(oci_core_drg_attachment.vcn.defined_tags) : strcontains(k, "Oracle-Tags")]),
    ])
    error_message = "this module must never itself declare an Oracle-Tags.* key on any gateway resource"
  }
}
